#
# Copyright © 2016-2022 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-config
  namespace: thingsboard
  labels:
    name: cassandra-config
data:
  probe: |
    if [[ $(nodetool -u cassandra -pw cassandrapassword status | grep $POD_IP) == *"UN"* ]]; then
       if [[ $DEBUG ]]; then
          echo "UN";
       fi
       exit 0;
    else
       if [[ $DEBUG ]]; then
          echo "Not Up";
       fi
       exit 1;
    fi
  jmxremote.password: |
    monitorRole QED
    controlRole R&D
    cassandra cassandrapassword
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: thingsboard
  labels:
    app: cassandra
spec:
  serviceName: cassandra
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - cassandra
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 1800
      containers:
      - name: cassandra
        image: cassandra:4.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        - containerPort: 9160
          name: thrift
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - nodetool drain
        env:
          - name: CASSANDRA_SEEDS
            value: "cassandra-0.cassandra.thingsboard.svc.cluster.local"
          - name: MAX_HEAP_SIZE
            value: 1024M
          - name: HEAP_NEWSIZE
            value: 256M
          - name: CASSANDRA_CLUSTER_NAME
            value: "Thingsboard Cluster"
          - name: CASSANDRA_DC
            value: "datacenter1"
          - name: CASSANDRA_RACK
            value: "Rack-Thingsboard-Cluster"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: LOCAL_JMX
            value: "no"
          - name: JVM_EXTRA_OPTS
            value: "-Dcom.sun.management.jmxremote.password.file=/config/jmxremote.password"
            # value: -Djava.rmi.server.hostname=$HOSTNAME.cassandra.thingsboard.svc.cluster.local -Dcom.sun.management.jmxremote.password.file=/config/jmxremote.password
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /config/ready-probe.sh
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
        - name: cassandra-config
          mountPath: /config                
        - name: cassandra-data
          mountPath: /var/lib/cassandra
          readOnly: false
      volumes:
        - name: cassandra-config
          configMap:
            name: cassandra-config
            items:
              - key: probe
                path: ready-probe.sh
                mode: 0777
              - key: jmxremote.password
                path: jmxremote.password
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
  namespace: thingsboard
spec:
  clusterIP: None
  ports:
    - port: 9042
      name: cql
    - port: 7199
      name: jmx
  selector:
    app: cassandra
---
