apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

# Specify desired availability zones. Don't forget to update the 'metadata.region' parameter to match availability zones.
availabilityZones: [us-east-1a,us-east-1b,us-east-1c]

metadata:
  name: thingsboard
  # Specify the desired aws region. Don't forget to update the 'availabilityZones' parameter to match the region.
  region: us-east-1
  version: "1.22"

managedNodeGroups:
  - name: tb-node
    instanceType: m5.xlarge
    desiredCapacity: 1
    maxSize: 1
    minSize: 1
    labels: { role: tb-node }
    # EC2 nodes will be launched in the private subnet and will not be accessible via SSH from the internet.
    privateNetworking: true
    # Uncomment the 'ssh' section and specify the correct name of the ec2 key (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html#having-ec2-create-your-key-pair).
    # Note: this is optional step. Required only if you plan to connect to your ec2 instances using SSH.
    #ssh:
      #allow: true
      #publicKeyPath: 'thingsboard-cluster'
# Uncomment this section if you plan to install and use Cassandra
#  - name: cassandra-1a
#    instanceType: m5.xlarge
#    desiredCapacity: 1
#    maxSize: 1
#    minSize: 1
#    labels: { role: cassandra }
#    availabilityZones: ["us-east-1a"]
#    privateNetworking: true
#  - name: cassandra-1b
#    instanceType: m5.xlarge
#    desiredCapacity: 1
#    maxSize: 1
#    minSize: 1
#    labels: { role: cassandra }
#    availabilityZones: ["us-east-1b"]
#    privateNetworking: true
#  - name: cassandra-1c
#    instanceType: m5.xlarge
#    desiredCapacity: 1
#    maxSize: 1
#    minSize: 1
#    labels: { role: cassandra }
#    availabilityZones: ["us-east-1c"]
#    privateNetworking: true
