#
# Copyright © 2016-2022 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: tb-coap-transport-config
  namespace: thingsboard
  labels:
    name: tb-coap-transport-config
data:
  conf: |
    export JAVA_OPTS="$JAVA_OPTS -Xlog:gc*,heap*,age*,safepoint=debug:file=/var/log/tb-coap-transport/${TB_SERVICE_ID}-gc.log:time,uptime,level,tags:filecount=10,filesize=10M"
    export JAVA_OPTS="$JAVA_OPTS -XX:+IgnoreUnrecognizedVMOptions -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/tb-coap-transport/${TB_SERVICE_ID}-heapdump.bin"
    export JAVA_OPTS="$JAVA_OPTS -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark"
    export JAVA_OPTS="$JAVA_OPTS -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:MaxTenuringThreshold=10"
    export JAVA_OPTS="$JAVA_OPTS -XX:+ExitOnOutOfMemoryError"
    export LOG_FILENAME=tb-coap-transport.out
    export LOADER_PATH=/usr/share/tb-coap-transport/conf

  logback: |
    <!DOCTYPE configuration>
    <configuration scan="true" scanPeriod="10 seconds">

        <appender name="fileLogAppender"
                  class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>/var/log/tb-http-transport/${TB_SERVICE_ID}.log</file>
            <rollingPolicy
                    class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
                <fileNamePattern>/var/log/tb-http-transport/${TB_SERVICE_ID}%d{yyyy-MM-dd}.%i.log</fileNamePattern>
                <maxFileSize>100MB</maxFileSize>
                <maxHistory>7</maxHistory>
                <totalSizeCap>700MB</totalSizeCap>
            </rollingPolicy>
            <encoder>
                <pattern>%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n</pattern>
            </encoder>
        </appender>

        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n</pattern>
            </encoder>
        </appender>

        <logger name="org.thingsboard.server" level="INFO" />

        <root level="INFO">
            <appender-ref ref="fileLogAppender"/>
            <appender-ref ref="STDOUT"/>
        </root>

    </configuration>


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tb-coap-transport
  namespace: thingsboard
spec:
  serviceName: "tb-coap-transport"
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app: tb-coap-transport
  template:
    metadata:
      labels:
        app: tb-coap-transport
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - tb-coap-transport
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: server
          imagePullPolicy: Always
          image: thingsboard/tb-coap-transport:3.3.4.1
          ports:
            - containerPort: 5683
              name: coap
              protocol: UDP
            - containerPort: 5684
              name: coaps
              protocol: UDP
          env:
            - name: TB_SERVICE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ZOOKEEPER_ENABLED
              value: "true"
            - name: ZOOKEEPER_URL
              value: "zookeeper:2181"
          envFrom:
            - configMapRef:
                name: tb-kafka-config
            - configMapRef:
                name: tb-redis-config
          volumeMounts:
            - mountPath: /config
              name: tb-coap-transport-config
            - mountPath: /var/log/tb-coap-transport
              name: tb-coap-transport-logs
      volumes:
        - name: tb-coap-transport-config
          configMap:
            name: tb-coap-transport-config
            items:
              - key: conf
                path:  tb-coap-transport.conf
              - key: logback
                path:  logback.xml
  volumeClaimTemplates:
    - metadata:
        name: tb-coap-transport-logs
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 750Mi
---
apiVersion: v1
kind: Service
metadata:
  name: tb-coap-loadbalancer
  namespace: thingsboard
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: tb-coap-transport
  ports:
    - port: 5683
      targetPort: 5683
      name: coap
      protocol: UDP
    - port: 5684
      targetPort: 5684
      name: coaps
      protocol: UDP
  externalIPs:
  - 192.168.49.2
---
# Uncomment for using NodePort
# apiVersion: v1
# kind: Service
# metadata:
#   name: tb-coap-transport
#   namespace: thingsboard
# spec:
#   selector:
#     app: tb-coap-transport
#   type: NodePort
#   ports:
#     - port: 5683
#       targetPort: 5683
#       nodePort: 31683
---
