apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: thingsboard
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    
    positions:
      filename: /tmp/positions.yaml
    
    clients:
      - url: http://loki-service.thingsboard.svc:3100/loki/api/v1/push
    
    scrape_configs:
      - job_name: varlog1
        static_configs:
          - targets:
              - localhost
            labels:
              job: varlog1
              __path__: /var/log/*log*
        pipeline_stages:
          - multiline:
              firstline: '^\[\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}\]'
              max_wait_time: 3s